apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chatbox-pdb
  labels:
    app: chatbox
    component: websocket
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: chatbox
      component: websocket
